import sqlite3

class AgriDatabase:
    """
    A unified connection tool that the CrewAI SQL Agent will use.
    Provides schema context dynamically so the LLM can generate accurate SQL,
    choose the proper table, and formulate JOINs for hybrid queries.
    """
    def __init__(self, db_path='data/processed/agri.db'):
        self.db_path = db_path

    def get_database_schema(self):
        """
        Returns a description of the tables in agri.db.
        Call this so the Agent knows which columns belong to which table.
        """
        schema = (
            "Database Name: agri.db\n\n"
            "Table 1: npk_data (soil and environmental conditions)\n"
            "Columns: Nitrogen, Phosphorus, Potassium, Temperature, Humidity, pH_Value, Rainfall, Crop, Soil_Type, Variety\n\n"
            "Table 2: crop_production (district-wise and state-wise yield data)\n"
            "Columns: Crop, Crop_Year, Season, State, Area, Production, Annual_Rainfall, Fertilizer, Pesticide, Yield\n\n"
            "Query Design Notes:\n"
            "- When the user asks about soil, temperature, or NPK requirements, query `npk_data`.\n"
            "- When the user asks about historical production, states, or crop yield amounts, query `crop_production`.\n"
            "- You can also JOIN both tables on the `Crop` column if the analytic query requires correlating soil data with state production.\n"
        )
        return schema

    def execute_sql_query(self, query_string):
        """Executes the raw SQL generated by the Agent and returns tabular results."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        try:
            cursor.execute(query_string)
            results = cursor.fetchall()
            columns = [description[0] for description in cursor.description]
            
            if not results:
                return "Query executed successfully, but returned 0 rows."
                
            return {"columns": columns, "results": results}
        except Exception as e:
            return {"sql_error": str(e)}
        finally:
            conn.close()

if __name__ == "__main__":
    import argparse
    import json
    
    parser = argparse.ArgumentParser(description="Test the Agri SQL Database execution tool.")
    parser.add_argument("--schema", action="store_true", help="Print the database schema")
    parser.add_argument("--query", type=str, help="Execute a raw SQL query against agri.db")
    
    args = parser.parse_args()
    db = AgriDatabase(db_path='data/processed/agri.db')
    
    if args.schema:
        print("--- DATABASE SCHEMA ---")
        print(db.get_database_schema())
    elif args.query:
        print(f"--- EXECUTING QUERY ---\n{args.query}\n")
        response = db.execute_sql_query(args.query)
        print("--- RESULTS ---")
        print(json.dumps(response, indent=2))
    else:
        print("Please provide --schema to view tables, or --query \"SELECT * FROM npk_data LIMIT 1\" to test execution.")
